import Head from "next/head";
import dynamic from "next/dynamic";

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>Нүүр | Trade Goodsec</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
